name: Test-Action

on: [push, pull_request, workflow_run, check_run]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
    
      - name: Test with unittest
        run: |
          python3 -m app.test
